[package]
name = "defmt-embassy-usb-logger"
version = "0.1.0"
edition = "2024"

[dependencies]
critical-section = "1.2.0"
defmt = "1.0.1"
embassy-futures = "0.1.1"
embassy-sync = "0.7.0"
embassy-time = "0.4.0"
embassy-usb = "0.5.0"
heapless = "0.8.0"
static_cell = "2.1.1"
